### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by nicholaskillin** [RASTRILL0/GloomhavenBattleGoals#1]
Hey, thanks for making this. I am the person that made the Discord bot and I recently had someone reach out to let me know that the URL's are no longer working. 

I tried the URL in the readme and it doesn't resolve either, but I see recent updates to the repo. Did the URL for this project change?

**Comment by RASTRILL0** [comment]
I had a hard drive failure and lost this server. Unfortunately, I won't have time to work on it anytime soon. I think everything is here on the github if anybody is interested in hosting it.

**Comment by nicholaskillin** [comment]
Oh no! That is a pain, sorry to hear about that. 

I may be able to help. I'm not super familiar with R though. I'm wondering if it's possible to host this on Heroku. We would need to find a build pack that it works with. Would you be able to provide me with some insight into the tech stack that is being used in this app? 

Thanks!

**Comment by nicholaskillin** [comment]
Actually, it looks like I may have gotten over those first hurdles. I'm experimenting with creating an `init.R` script that will install the needed packages to run this on Heroku. I assume that these are the only packages needed?

```
library(shiny)
library(shinyjs)
library(shinythemes)
library(tibble)
library(dplyr)
```

**Comment by RASTRILL0** [comment]
Yes, that should be everything.

**Comment by nicholaskillin** [comment]
Alright, I have this up and running on Heroku. You can view it here:

https://gloomhaven-battle-goals.herokuapp.com.

I tried to push a new branch to your repo to open up a PR for you to take a look at, but I don't have permission. I'd be happy to open a PR for you if you want to open up the ability for me to do so.

**Comment by RASTRILL0** [comment]
I’ve added you as a collaborator. Let me know if you need anything else. Thanks for getting this up and running again.

**Comment by nicholaskillin** [comment]
No worries! Also, if you want to maintain control over this I can transfer the Heroku app to you. You would need to make an account if you don't already have one and then let me know what email address you used on your account. It's totally free.

You would also be able to hook up the Heroku app to this Github repo at that point so that anytime you push changes to master it automatically deploys those changes to Heroku.

**Comment by nicholaskillin** [comment]
Okay, so I updated the Discord bot to point to the new domain and it looks like there are still issues. Now when I follow the URL generated by the bot none of the settings from the URL are loaded into the UI. Also when I use the app normally and click on "Invite Party" nothing happens. So I assume the entire bookmark system is shot.

Honestly with this being in R, I'm not really sure how that was ever set up or working. I didn't see anything obvious looking through the existing code.

Is this a project that you are still interested in maintaining? If so, I could use some help getting that back up and running.

**Comment by RASTRILL0** [comment]
The tool should be up and running at ghbg.duckdns.org 

I reverted back to the single file because of the bookmarking issue you had. I've got my server running again so we should be good for now.

**Comment by nicholaskillin** [comment]
Thanks! I just updated the Discord bot with your new URL.
